module.exports = [
    {
      "No": 1,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "01",
      "CLASS_NAME": "PART",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101211016,
      "DESC_TH": "PMART สันนอกหมูแล็ป",
      "UOM_PURCHASE": "KG",
      "UOM_SALE": "KG",
      "UOM CONVERSION": 1,
      "Mim_order": 10,
      "LV": 1,
      "SV": 1,
      "VAT": "N",
      "COST": 125,
      "SP": 125
    },
    {
      "No": 2,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "01",
      "CLASS_NAME": "PART",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101211017,
      "DESC_TH": "PMART สันคอหมูแล็ป",
      "UOM_PURCHASE": "KG",
      "UOM_SALE": "KG",
      "UOM CONVERSION": 1,
      "Mim_order": 10,
      "LV": 1,
      "SV": 1,
      "VAT": "N",
      "COST": 129,
      "SP": 129
    },
    {
      "No": 3,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231005,
      "DESC_TH": "PMART สันคอหมูสไลด์",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 136,
      "SP": 136
    },
    {
      "No": 4,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231006,
      "DESC_TH": "PMART สันคอหมูสไลด์ (ชาบู)",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 12,
      "Mim_order": 1,
      "LV": 12,
      "SV": 1,
      "VAT": "N",
      "COST": 149,
      "SP": 149
    },
    {
      "No": 5,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231007,
      "DESC_TH": "PMART หมูสามชั้นสไลด์ A",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 12,
      "Mim_order": 1,
      "LV": 12,
      "SV": 1,
      "VAT": "N",
      "COST": 142,
      "SP": 142
    },
    {
      "No": 6,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231008,
      "DESC_TH": "PMART หมูสามชั้นสไลด์ B",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 12,
      "Mim_order": 1,
      "LV": 12,
      "SV": 1,
      "VAT": "N",
      "COST": 125,
      "SP": 125
    },
    {
      "No": 7,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231009,
      "DESC_TH": "PMART เนื้อหมูนุ่ม",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 148,
      "SP": 148
    },
    {
      "No": 8,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231010,
      "DESC_TH": "PMART เนื้อหมูหมักซอสปรุงรส",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 148,
      "SP": 148
    },
    {
      "No": 9,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231011,
      "DESC_TH": "PMART หมูสามชั้นหมักซอสน้ำมันงา",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 99,
      "SP": 99
    },
    {
      "No": 10,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231012,
      "DESC_TH": "PMART หมูสามชั้นหมักซอสพริกไทยดำ",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 99,
      "SP": 99
    },
    {
      "No": 11,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231013,
      "DESC_TH": "PMART หมูหมักซอสบาร์บีคิว",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 75,
      "SP": 75
    },
    {
      "No": 12,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231014,
      "DESC_TH": "PMART หมูหมักน้ำมันงา",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 75,
      "SP": 75
    },
    {
      "No": 13,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231015,
      "DESC_TH": "PMART หมูหมักนุ่ม",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 73,
      "SP": 73
    },
    {
      "No": 14,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231016,
      "DESC_TH": "PMART หมูหมักพริกไทยดำ",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 75,
      "SP": 75
    },
    {
      "No": 15,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231017,
      "DESC_TH": "PMART หมูหมักไวน์แดง",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 10,
      "Mim_order": 1,
      "LV": 10,
      "SV": 1,
      "VAT": "N",
      "COST": 75,
      "SP": 75
    },
    {
      "No": 16,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231018,
      "DESC_TH": "PMART หมูเบคอนสด",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 8,
      "Mim_order": 1,
      "LV": 8,
      "SV": 1,
      "VAT": "N",
      "COST": 179,
      "SP": 179
    },
    {
      "No": 17,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231019,
      "DESC_TH": "PMART ตับหมูสไลด์",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 12,
      "Mim_order": 1,
      "LV": 12,
      "SV": 1,
      "VAT": "N",
      "COST": 68,
      "SP": 68
    },
    {
      "No": 18,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231020,
      "DESC_TH": "PMART มันหมูหั่นเต๋า",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 12,
      "Mim_order": 1,
      "LV": 12,
      "SV": 1,
      "VAT": "N",
      "COST": 65,
      "SP": 65
    },
    {
      "No": 19,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231021,
      "DESC_TH": "PMART เซียงจี๊หมูสไลด์",
      "UOM_PURCHASE": "BOX",
      "UOM_SALE": "PACK",
      "UOM CONVERSION": 12,
      "Mim_order": 1,
      "LV": 12,
      "SV": 1,
      "VAT": "N",
      "COST": 75,
      "SP": 75
    },
    {
      "No": 20,
      "DIVISION": "01",
      "DIVISION_NAME": "LAND",
      "DEPARTMENT_CODE": "01",
      "DEPARTMENT_NAME": "PORK",
      "SUBDEPARTMENT_CODE": "02",
      "SUBDEPARTMENT_NAME": "LOCAL",
      "CLASS_CODE": "03",
      "CLASS_NAME": "MIXED",
      "SUBCLASS_CODE": "01",
      "SUBCLASS_NAME": "FROZEN",
      "ITEM CODE": 101231022,
      "DESC_TH": "PMART หมูบด",
      "UOM_PURCHASE": "KG",
      "UOM_SALE": "KG",
      "UOM CONVERSION": 1,
      "Mim_order": 10,
      "LV": 1,
      "SV": 1,
      "VAT": "N",
      "COST": 50,
      "SP": 50
    }
  ]